[build]
builder = "nixpacks"
buildCommand = "npm run build && npm run build:server"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[database]
name = "aiclubx"